{% set name = "marko" %}
{% set version = "1.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/marko-{{ version }}.tar.gz
  sha256: d467c3ad450be693505cb8eb7054718efe3f14fccc2310588f9bc9c1d992ef94

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - marko=marko.cli:main

requirements:
  host:
    - pip
    - python >=3.6
    - pdm-pep517
  run:
    - python >=3.6

test:
  imports:
    - marko
  commands:
    - pip check
    - marko --help
  requires:
    - pip

about:
  home: https://pypi.org/project/marko/
  summary: A markdown parser with high extensibility.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - asford
