{% set name = "marko" %}
{% set version = "1.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/marko-{{ version }}.tar.gz
  sha256: 6f10dec07eaf098e22554d851b88251167bbc38d214a5ef74b733e62d9da7bbe

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  entry_points:
    - marko=marko.cli:main

requirements:
  host:
    - pip
    - python
    - pdm-pep517
  run:
    - python
    - python-slugify
    - pygments

test:
  source_files:
    - tests
  imports:
    - marko
  commands:
    - pip check
    - marko --help
    - pytest -vv tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/frostming/marko
  dev_url: https://github.com/frostming/marko/
  doc_url: https://marko-py.readthedocs.io/
  summary: A markdown parser with high extensibility.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    Marko is a markdown parser written in pure Python that complies with CommonMark's spec v0.30.
    It is designed to be highly extensible.

extra:
  recipe-maintainers:
    - xhochy
    - asford
